### ISSUE TITLE
Fetching images at slow speed

### ISSUE THREAD

**Issue by Coding4What** [DamnScallion/AI-Gen-Image#1]
Hi mate. I went through the website and I found images fetched at slow speed. I have checked the request, it took around 1 min to get the image data. Hopefully, you can improve it later. Btw it's a good project:)

**Comment by GeorgeLuo404** [comment]
Fanks for pointing that out mate. The project database currently runs on a free MongoDB cluster🤣. And all images have been stored on Cloudinary(CDN). This might be the main reason cause the slow fetching speed. I will try to optimize the speed issue in the future. Anyway, best regard mate.😎
